# Generated by Django 3.1.7 on 2021-03-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nivensapp', '0002_auto_20210315_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PointTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('break_time', models.DateTimeField(blank=True, null=True)),
                ('back_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nivensapp.employee')),
            ],
            options={
                'verbose_name': 'Ponto',
                'verbose_name_plural': 'Pontos',
                'db_table': 'ponto',
            },
        ),
    ]
