# Generated by Django 3.1.7 on 2021-08-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nivensapp', '0005_auto_20210802_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
