# Generated by Django 3.1.7 on 2021-08-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nivensapp', '0006_delete_report'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pointtime',
            unique_together={('employee', 'day')},
        ),
    ]
